default:
    adapter: mysql2
    database: heroku_3449a5f3cd5d4b3
    username: b727e6033000ab
    password: 8a32cd40
    host: us-cdbr-iron-east-04.cleardb.net
development:
    adapter: mysql2
    database: heroku_3449a5f3cd5d4b3
    username: b727e6033000ab
    password: 8a32cd40
    host: us-cdbr-iron-east-04.cleardb.net
production:
    adapter: mysql2
    database: heroku_3449a5f3cd5d4b3
    username: b727e6033000ab
    password: 8a32cd40
    host: us-cdbr-iron-east-04.cleardb.net